name: Angular CI/CD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '16'
            - name: Install dependencies
              run: npm install
            - name: Build the Angular app
              run: npm run build-prod
            - name: Compress dist folder
              run: tar -czf dist.tar.gz dist/
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: dist
                path: dist.tar.gz